### ISSUE TITLE
シンボリックリンク先でのpwd

### ISSUE THREAD

**Issue by osorosia** [katataku/minishell#116]
-Pか-Lか

**Comment by osorosia** [comment]
https://qiita.com/ko1nksm/items/fbc20859354196722cfb
POSIXだと-Lだけど、これをみるとminishellではどっちでもいいような気がした

**Comment by katataku** [comment]
@osorosia 気づいてるかもですが、多分違うリポジトリにIssue立ててますー

**Comment by osorosia** [comment]
！！！
すみませんでした＞＜

**Comment by katataku** [comment]
@osorosia お気になさらず！minishellがんばってください！！

[![LGTMeow](https://lgtm-images.lgtmeow.com/2021/11/16/22/6cb07bce-67a8-496e-a6c5-febfb435a9a5.webp)](https://lgtmeow.com)
