### ISSUE TITLE
builtin export

### ISSUE THREAD

**Issue by hayashi-ay** [katataku/minishell#59]

**Comment by katataku** [comment]
環境変数はnameである。

nameの定義：
A word consisting solely of letters, numbers, and underscores, and beginning with a letter or underscore. Names are used as shell variable and function names.

**Comment by katataku** [comment]
```bash
bash-3.2$ export a42=FT
bash-3.2$ export _42=FT
bash-3.2$ export 42=FT
bash: export: `42=FT': not a valid identifier
```
