### ISSUE TITLE
$変数展開

### ISSUE THREAD

**Issue by katataku** [katataku/minishell#71]
${}は対応しない

**Comment by hayashi-ay** [comment]
@katataku exitが5poitほどあったので今週このチケットは落としちゃおうと思います。

**Comment by hayashi-ay** [comment]
あと#72も重そう。

**Comment by hayashi-ay** [comment]
一旦assign外しちゃいますね〜〜

**Comment by hayashi-ay** [comment]
シェルの変数名の定義
> A word consisting solely of letters, numbers, and underscores, and beginning with a letter or underscore. Names are used as shell variable and function names. Also referred to as an identifier.

**Comment by hayashi-ay** [comment]
```bash
$ A=$HOME
$ B=$A
$ C=$B
$ echo $C
/Users/hayashi-ay
```

**Comment by hayashi-ay** [comment]
展開時はモードを切り替えて読んでいく感じの挙動になりそう。

```bash
echo $HOGE++'$HOGE'++"$HOGE"
XXX++$HOGE++XXX
```

**Comment by hayashi-ay** [comment]
ダブルクオートで囲われていると空白もワードとみなす、囲われていないと区切られる。

```bash
$ HOGE="ls -la"
$ "$HOGE"
-bash: ls -la: command not found
$ $HOGE
total 0
drwxr-xr-x   2 hayashi-ay  staff    64  3 15 14:38 .
drwxr-xr-x+ 64 hayashi-ay  staff  2048  3 15 14:38 ..
```

**Comment by hayashi-ay** [comment]
とりあえず今回は細かいケースは考えずただ置換するところまで。

**Comment by hayashi-ay** [comment]
$0~9は変数としてみなさない
