### ISSUE TITLE
字句解析

### ISSUE THREAD

**Issue by katataku** [katataku/minishell#9]

**Comment by katataku** [comment]
@hayashi-ay 
token分解処理の戻り値ですが、以下のように話していましたが、
以下を含むような構造体を返すような実装に、変更してもいいでしょうか。

```
*int { T_WORD, T_ANP, T_ANP, T_WORD, T_PIPE, T_WORD, T_EOF}
*word { "date", NULL, NULL, "pwd", NULL ,"cat", NULL }
```

**Comment by hayashi-ay** [comment]
OKです。一緒にまとめちゃった方が扱いやすいですか？

**Comment by katataku** [comment]
多分、扱いやすそうです。多分笑

あと、表現したい内容が増えるかもと思ってます。
例えば「ここはダブルクオートで囲まれたT_WORDだよ」とか。
その時の拡張性考えてましたー

**Comment by katataku** [comment]
「tokenの数を数えるのは大変」という問題にぶつかりました！
「t_token型を持つ線形リスト」にしてもいいですか！？

**Comment by hayashi-ay** [comment]
通知が来た気がしました。
「tokenの数を数えるのは大変」というのは何が大変なのですか？
動的配列にしちゃえば、配列のメモリ管理周りはそんなに意識しなくてもいいかなーと思っています。

**Comment by hayashi-ay** [comment]
リストで持っちゃうとexecveに渡すときに再度加工しないといけないので配列の方がいい気がしてます。

**Comment by katataku** [comment]
一回通知行きました。
先に計算しちゃえばいいやと気づいたので、配列案で続行します！

**Comment by katataku** [comment]
括弧"（）{}"ってトークン化必要ですか？

特に必要な要件が明記されてないので不要かなと思ってます。

**Comment by hayashi-ay** [comment]
`()`は要らなさそうな気はします。
`{}`は$変数の展開に含まれると解釈もできそう？

```
echo $HOME
/Users/hayashi-ay
$ echo $HOMEALONE

$ echo ${HOME}ALONE
/Users/hayashi-ayALONE
```

**Comment by katataku** [comment]
>  `{}`は$変数の展開に含まれると解釈もできそう？
たしかに！対応しました

**Comment by katataku** [comment]
-はスペシャルキャラクター

**Comment by hayashi-ay** [comment]
そういえばビルトインで`cd -`とか対応する必要あるんですかね〜？
